### ISSUE TITLE
File paths in inspectcode XML-report are broken on some systems

### ISSUE THREAD

**Issue by ryskov** [fakesharper/fakesharper#1]
The filepaths in the XML generated by inspectcode uses backward-slashes which results in 'File not found' errors on MacOS (and most likely other systems too). 

A good fix could be to have the extension normalize the filepaths based on the OS at parse-time.

Example from the XML:

```xml
<Issue TypeId="MemberCanBePrivate.Global" File="TestProject\Helpers\Test.cs" Offset="751-757" Line="22" Message="Property 'PractitionerEventHelper' can be made private" />
```

This will try to open `/some/base/path/TestProject\Helpers\Test.cs` which is not valid.

**Comment by ryskov** [comment]
Great extension btw! Hoping to get this resolved so i can really start using it :)

**Comment by jaqra** [comment]
New version released. Can you check and close if it is working please

**Comment by ryskov** [comment]
This is working as expected now :+1:
