### ISSUE TITLE
Install ReSharper command line tool via .NET Core

### ISSUE THREAD

**Issue by hampoelz** [fakesharper/fakesharper#13]
It's much easier to install the `ReSharper command line tool` through the `Dotnet command` (as documented on https://www.jetbrains.com/help/resharper/ReSharper_Command_Line_Tools.html#install-and-use-resharper-command-line-tools-as-net-core-tools)  than it is to download it, put it in a folder, and change the PATH property.
And it also doesn't happen that the tool can't find MS Build (had this problem).

You may be able to install the tools automatically if they are not available on your computer when you run the extension.

**Comment by jaqra** [comment]
@hampoelz thank you so much! feel free to send pr or i will implement this soon

**Comment by hampoelz** [comment]
@jaqra Unfortunately, I don't really have time to create a pr right now. :/
