### ISSUE TITLE
Not an actual issue

### ISSUE THREAD

**Issue by thecrazy** [fakesharper/fakesharper#19]
Sorry to ask this here but I dont know how else to conctact you and have been looking for this for a while...

How do you get that nice c# syntax highligthing in your screenshots on the main page? https://github.com/fakesharper/fakesharper

Do you use an extention and custom theme? Cause my syntax highligting in vscode is no where near this detailed.

Thank you.

**Comment by jaqra** [comment]
Hi @thecrazy , it's [one monokai theme](https://marketplace.visualstudio.com/items?itemName=azemoh.one-monokai)

**Comment by thecrazy** [comment]
Thank you!
